{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-secret
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    diploma.demo/description: "Example only. Use External Secrets, Vault or Azure Key Vault in production."
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

