global:
  domain: argocd.diploma-demo.local

configs:
  params:
    server.insecure: true
  cm:
    application.resourceTrackingMethod: annotation

server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.diploma-demo.local
    path: /
    pathType: Prefix

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

