nameOverride: demo-web
replicaCount: 1
controller:
  labels:
    environment: dev
    stack: demo
    component: demo-web
podLabels:
  environment: dev
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacrauto.azurecr.io/diploma-demo-web
  tag: dev-c4a93d5-1
config:
  APP_NAME: diploma-demo-web
  APP_ENV: dev
  APP_VERSION: dev-c4a93d5-1
  DEPLOYMENT_TIMESTAMP: '2026-05-07T00:58:55Z'
  GIT_SHA: c4a93d5bda018e0e9124633c28ea2cd9c1177ff2
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-dev
ingress:
  enabled: true
  className: nginx
  host: dev.diploma-demo.local
  extraHosts:
  - dev.9.163.160.100.sslip.io
resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuAverageUtilization: 70
