nameOverride: demo-web
replicaCount: 1
controller:
  labels:
    environment: dev
    stack: demo
    component: demo-web
podLabels:
  environment: dev
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacrauto.azurecr.io/diploma-demo-web
  tag: dev-94cd8b7-2
config:
  APP_NAME: diploma-demo-web
  APP_ENV: dev
  APP_VERSION: dev-94cd8b7-2
  DEPLOYMENT_TIMESTAMP: '2026-05-09T17:42:30Z'
  GIT_SHA: 94cd8b7ed7907e9b0a8376ca9dae8f6b7c6cbc9b
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-dev
ingress:
  enabled: true
  className: nginx
  host: dev.diploma-demo.local
  extraHosts:
  - dev.20.50.187.20.sslip.io
resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuAverageUtilization: 70
