nameOverride: demo-web
replicaCount: 2
controller:
  labels:
    environment: stage
    stack: demo
    component: demo-web
podLabels:
  environment: stage
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacrauto.azurecr.io/diploma-demo-web
  tag: stage-c4a93d5-1
config:
  APP_NAME: diploma-demo-web
  APP_ENV: stage
  APP_VERSION: stage-c4a93d5-1
  DEPLOYMENT_TIMESTAMP: '2026-05-07T00:58:59Z'
  GIT_SHA: c4a93d5bda018e0e9124633c28ea2cd9c1177ff2
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-stage
ingress:
  enabled: true
  className: nginx
  host: stage.diploma-demo.local
  extraHosts:
  - stage.9.163.160.100.sslip.io
resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuAverageUtilization: 65
