nameOverride: demo-web
replicaCount: 3
controller:
  labels:
    environment: prod
    stack: demo
    component: demo-web
podLabels:
  environment: prod
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacrauto.azurecr.io/diploma-demo-web
  tag: prod-94cd8b7-2
config:
  APP_NAME: diploma-demo-web
  APP_ENV: prod
  APP_VERSION: prod-94cd8b7-2
  DEPLOYMENT_TIMESTAMP: '2026-05-09T17:42:41Z'
  GIT_SHA: 94cd8b7ed7907e9b0a8376ca9dae8f6b7c6cbc9b
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-prod
ingress:
  enabled: true
  className: nginx
  host: diploma-demo.local
  hostlessRule: true
  extraHosts:
  - prod.20.50.187.20.sslip.io
resources:
  requests:
    cpu: 100m
    memory: 160Mi
  limits:
    cpu: 750m
    memory: 512Mi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuAverageUtilization: 60
