nameOverride: demo-web
replicaCount: 3
controller:
  labels:
    environment: prod
    stack: demo
    component: demo-web
podLabels:
  environment: prod
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacrauto.azurecr.io/diploma-demo-web
  tag: prod-3be3236-3
config:
  APP_NAME: diploma-demo-web
  APP_ENV: prod
  APP_VERSION: prod-3be3236-3
  DEPLOYMENT_TIMESTAMP: '2026-05-16T13:52:04Z'
  GIT_SHA: 3be32365d18173509b7180dc4d56bad5b6de2e51
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-prod
ingress:
  enabled: true
  className: nginx
  host: diploma-demo.local
  hostlessRule: true
  extraHosts:
  - prod.20.123.231.59.sslip.io
resources:
  requests:
    cpu: 100m
    memory: 160Mi
  limits:
    cpu: 750m
    memory: 512Mi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuAverageUtilization: 60
