nameOverride: demo-web
replicaCount: 2
controller:
  labels:
    environment: stage
    stack: demo
    component: demo-web
podLabels:
  environment: stage
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacrauto.azurecr.io/diploma-demo-web
  tag: stage-3be3236-3
config:
  APP_NAME: diploma-demo-web
  APP_ENV: stage
  APP_VERSION: stage-3be3236-3
  DEPLOYMENT_TIMESTAMP: '2026-05-16T13:51:59Z'
  GIT_SHA: 3be32365d18173509b7180dc4d56bad5b6de2e51
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-stage
ingress:
  enabled: true
  className: nginx
  host: stage.diploma-demo.local
  extraHosts:
  - stage.20.123.231.59.sslip.io
resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuAverageUtilization: 65
